version: 2
jobs:
  build:
    docker:
      - image: bbrady/circleci-env:0.0.0

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "93:04:59:b0:0c:92:10:25:5a:5e:2b:0e:71:f8:13:98"
      - run: |
          sha=`git rev-parse HEAD`
          sh gen.sh > /tmp/env
          git config --global user.email "bryan.brady@gmail.com"
          git config --global user.name "bryan brady"
          git clone git@github.com:bryanbrady/asdf-sh.git
          cd asdf-sh
          cp /tmp/env .
          if ! git diff --exit-code; then
            git add -u
            git commit -m "update env for $sha"
            git push origin master
          fi
